language: r
cache: packages

matrix:
  include:
    - r: oldrel
      os: linux
    - r: oldrel
      os: osx
    - r: release
      os: linux
      after_success: Rscript -e 'covr::coveralls(type = "all")'
    - r: release
      os: osx
