name: R-CMD-check-backwards

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  R-CMD-check-backwards:
    runs-on: windows-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: true

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.0.2'
          use-public-rspm: true

      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_cran(
            c("checkmate", "data.table", "R6", "dygraphs", "fasttime", "RColorBrewer", "RcppCCTZ", "runner", "units", "rcmdcheck"),
            repos = "https://mran.microsoft.com/snapshot/2020-06-22",
            type = "win.binary",
            dependencies = TRUE
          )
          remotes::install_deps(
            dependencies = TRUE,
            type = "win.binary",
            upgrade = "never"
          )
        shell: Rscript {0}

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
          _R_CHECK_FORCE_SUGGESTS_: false
        run: |
          rcmdcheck::rcmdcheck(
            args = c("--no-manual", "--as-cran"),
            build_args = "--no-manual",
            check_dir = "check",
            error_on = "warning"
          )
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
